#!/bin/sh
PTH=`pwd`/
DEP=dependencies/
CLS=classes/
#JVA=Java/


if cygpath -w / >/dev/null 2>/dev/null; then
  CLASSPATH="main.jar;$CLASSPATH"
else
  CLASSPATH="main.jar:$CLASSPATH"
fi
java -cp .:$PTH$DEP*:$PTH$CLS  Main
